### ISSUE TITLE
请求在GitHub release中生成搜狗新词，更新词典方式考虑使用rime的plum

### ISSUE THREAD

**Issue by qixing-jk** [gshang2017/rime-dict#1]
### 生成[搜狗新词](https://pinyin.sogou.com/dict/detail/index/4)
未找到搜狗新词的生成方式，只看到nas docker方式说可以生成，希望也能支持GitHub生成，或许作者大大也可以考虑，定期nas自动提交到GitHub？

### [plum](https://github.com/rime/plum)更新方式
[示例](https://github.com/iDvel/rime-ice?tab=readme-ov-file#%E4%B8%9C%E9%A3%8E%E7%A0%B4-plum)

**Comment by gshang2017** [comment]
搜狗新词更新太频繁，所以才用docker方式自动检测更新生成。 新词如果无法保持最新其实没太大价值。如果有nas建议布署在nas里用同步软件同步到rime文件夹，这样全平台可用，没有也可以在电脑上直接布署。这样可以保持新词最新。 

https://github.com/gshang2017/docker/tree/master/rime-sogou

**Comment by qixing-jk** [comment]
主要是Windows环境下，尝试Python在conda的环境下无法完整环境的配置，也没有现成的Linux环境，只能考虑云端执行
GitHub Actions也没相关新词生成的原因是因为执行时间会过长吗？还是其实没有在GitHub提供代码，因为我在此项目中搜索SOGOU_SCEL_UPDATE_AUTO环境变量并未找到

**Comment by gshang2017** [comment]
生成词库代码在
https://github.com/gshang2017/docker/tree/master/rime-sogou/root/usr/local/rime_update 里
sogou_scel_update.py 

但是只能在linux下才行。
你可以安装Windows的WSL环境运行。

或者你可以下载词库及软件

https://github.com/studyzy/imewlconverter

自己转换成rime文件。
这是模板
[pinyin_simp.sogou_pop.dict.yaml.zip](https://github.com/gshang2017/rime-dict/files/13741822/pinyin_simp.sogou_pop.dict.yaml.zip)
