### ISSUE TITLE
群晖上运行，无法更新搜狗词库；出错

### ISSUE THREAD

**Issue by shine85** [gshang2017/rime-dict#2]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pinyin.sogou.com', port=443): Max retries exceeded with url: /dict/cate/index/1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f777ad13040>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by gshang2017** [comment]
更新了下，你可以试试。更新搜狗词库时间会很长，不建议这样做。搜狗增加的大多都是游戏和影视词库。

**Comment by shine85** [comment]
![123](https://github.com/gshang2017/rime-dict/assets/73932625/216b1aa8-e347-4bbc-a4da-1c68c1cec8f9)
还是这样子耶。

**Comment by gshang2017** [comment]
没测试出这样的错误，可能是访问过多触发了搜狗反爬虫导致的，词库已经更新到最新版了，你可以不用更新。
