### ISSUE TITLE
可以出一个合并去重的单文件词库文件吗

### ISSUE THREAD

**Issue by xiaoyixiao369** [gshang2017/rime-dict#3]
可以出一个合并去重的单文件词库文件吗

**Comment by Mircc** [comment]
哈哈哈 同需求

**Comment by gshang2017** [comment]
2024.06.14版压缩包里的total_dict.dict文件

**Comment by xiaoyixiao369** [comment]
![PixPin_2024-06-15_17-29-01](https://github.com/gshang2017/rime-dict/assets/2564493/87e3aca2-2053-4956-b4cb-c11aecc1dbd5)
红框圈住的这些应该是搜狗的U模式的吧，应该是不需要的

**Comment by gshang2017** [comment]
2024.06.15版压缩包里的no-chaizi-total-dict文件
